name: Release

on:
  push:
    tags:
      - "fumadocs-v*"

permissions:
  contents: write
  id-token: write
  deployments: write

jobs:
  publish-fumadocs:
    permissions:
      contents: write
      id-token: write
      deployments: write
    uses: ChrisLally/lally-cli/.github/workflows/release-publish.yml@main
    with:
      tag_prefix: "fumadocs-v"
      install_args: "--no-frozen-lockfile --config.auto-install-peers=false"
